name: Publish Package to npmjs
on:
  release:
    types: [published]
jobs:
  npm-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm run tsc
      - name: Authenticate with private NPM package
        run: echo "//registry.npmjs.org/:_authToken=${{secrets.NPM_PUBLISH_TABLET}}" > .npmrc
      - name: set the release tag as the version
        env:
          RELEASE_VERSION: ${{github.ref.tag}}
        run: npm version $RELEASE_VERSION
      - run: npm publish
